# Generated by Django 4.1.7 on 2023-04-02 01:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personnel", "0001_initial"),
        ("acceuil", "0005_pays_ville_delete_pays_dim_delete_ville_dim"),
        ("inventaires_et_stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=50)),
                ("nom", models.CharField(max_length=50)),
                (
                    "nomEntreprise",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("adresse", models.CharField(blank=True, max_length=100, null=True)),
                ("telephone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("info", models.CharField(max_length=200)),
                (
                    "pays",
                    models.ForeignKey(
                        blank=True,
                        default=127,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="acceuil.pays",
                    ),
                ),
                (
                    "ville",
                    models.ForeignKey(
                        blank=True,
                        default=22187,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="acceuil.ville",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Devis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(
                            2023, 4, 2, 1, 53, 47, 298460, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("remise", models.FloatField(blank=True, default=0, null=True)),
                (
                    "agentCommercial",
                    models.ForeignKey(
                        default=999,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="createurDevis",
                        to="personnel.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DevisArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.FloatField(default=0)),
                (
                    "article",
                    models.ForeignKey(
                        default=999,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventaires_et_stock.article",
                    ),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        default=999,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventes.devis",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="devis",
            name="article",
            field=models.ManyToManyField(
                through="ventes.DevisArticle", to="inventaires_et_stock.article"
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="client",
            field=models.ForeignKey(
                default=999,
                on_delete=django.db.models.deletion.RESTRICT,
                to="ventes.client",
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="responsable",
            field=models.ForeignKey(
                default=999,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="responsableTravail",
                to="personnel.employe",
            ),
        ),
    ]
