# Generated by Django 4.1.7 on 2023-04-02 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0002_alter_devis_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="info",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="devis",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 4, 2, 17, 53, 10, 620911, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
