# Generated by Django 4.1.7 on 2023-03-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="pays_dim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pays", models.CharField(max_length=50)),
                ("abbrev", models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={"db_table": '"communs". "pays_dim"', "managed": False,},
        ),
    ]
