# Generated by Django 4.1.7 on 2023-03-26 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("acceuil", "0004_ville_dim"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pays", models.CharField(max_length=50)),
                ("abbrev", models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ville",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ville", models.CharField(max_length=50)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                (
                    "pays",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acceuil.pays"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Pays_Dim",),
        migrations.DeleteModel(name="Ville_Dim",),
    ]
