# Generated by Django 4.1.7 on 2023-04-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_terrain_photo1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disponibilite",
            name="indDisponible",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="terrain",
            name="photo1",
            field=models.ImageField(blank=True, null=True, upload_to="terrains/"),
        ),
        migrations.AlterField(
            model_name="terrain",
            name="photo2",
            field=models.ImageField(blank=True, null=True, upload_to="terrains/"),
        ),
        migrations.AlterField(
            model_name="terrain",
            name="photo3",
            field=models.ImageField(blank=True, null=True, upload_to="terrains/"),
        ),
        migrations.AlterField(
            model_name="terrain",
            name="photo4",
            field=models.ImageField(blank=True, null=True, upload_to="terrains/"),
        ),
        migrations.AlterField(
            model_name="terrain",
            name="photo5",
            field=models.ImageField(blank=True, null=True, upload_to="terrains/"),
        ),
    ]
