# Generated by Django 4.1.7 on 2023-02-20 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "depParent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="gestionPersonnel.departement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "numeroEmploye",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prenom", models.CharField(max_length=50)),
                ("nom", models.CharField(max_length=50)),
                ("dateNaissance", models.DateField()),
                (
                    "sexe",
                    models.CharField(
                        choices=[("H", "HOMME"), ("F", "FEMME")], max_length=1
                    ),
                ),
                ("adresseDom", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "ville",
                    models.CharField(
                        blank=True, default="Bamako", max_length=50, null=True
                    ),
                ),
                (
                    "pays",
                    models.CharField(
                        blank=True, default="Mali", max_length=50, null=True
                    ),
                ),
                (
                    "dateAjout",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            2,
                            20,
                            17,
                            15,
                            50,
                            437440,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="gestionPersonnel.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployePoste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateDebut", models.DateField(default="1991-01-01")),
                ("dateFin", models.DateField(default="9999-12-31")),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionPersonnel.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TermPaie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.FloatField(default=0)),
                ("bonus", models.FloatField(default=0)),
                ("dateDebut", models.DateField(default="1991-01-01")),
                ("dateFin", models.DateField(default="9999-12-31")),
                (
                    "raisonPaie",
                    models.CharField(default="Termes actuels", max_length=500),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionPersonnel.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TermEmploi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("P", "Permanent"), ("C", "Contractuel")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("dateDebut", models.DateField()),
                ("dateFin", models.DateField(default="9999-12-31")),
                (
                    "raisonFin",
                    models.CharField(default="Termes actuels", max_length=100),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionPersonnel.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Poste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("categorie", models.CharField(max_length=100)),
                ("niveau", models.IntegerField()),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="gestionPersonnel.departement",
                    ),
                ),
                (
                    "employePoste",
                    models.ManyToManyField(
                        through="gestionPersonnel.EmployePoste",
                        to="gestionPersonnel.employe",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employeposte",
            name="poste",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="gestionPersonnel.poste",
            ),
        ),
    ]
