# Generated by Django 4.1.6 on 2023-02-05 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPersonnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='dateAjout',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 22, 9, 18, 484821, tzinfo=datetime.timezone.utc)),
        ),
    ]
