# Generated by Django 4.1.7 on 2023-02-22 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionPersonnel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="dateAjout",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 22, 12, 3, 47, 85641, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
