# Generated by Django 4.1.6 on 2023-02-05 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPersonnel', '0003_alter_employe_dateajout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='dateAjout',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 22, 11, 30, 217322, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employe',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
    ]
