# Generated by Django 4.1.6 on 2023-02-05 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPersonnel', '0005_alter_employe_dateajout_alter_employe_datenaissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='dateAjout',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 22, 20, 48, 675085, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employe',
            name='dateEmbauche',
            field=models.DateField(blank=True, null=True),
        ),
    ]
