# Generated by Django 4.1.6 on 2023-02-05 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPersonnel', '0006_alter_employe_dateajout_alter_employe_dateembauche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='dateAjout',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 22, 22, 42, 479549, tzinfo=datetime.timezone.utc)),
        ),
    ]
