# Generated by Django 4.1 on 2023-02-11 21:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("gestionPersonnel", "0007_alter_employe_dateajout"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "depParent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="gestionPersonnel.departement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployePoste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateDebut", models.DateField(default="1991-01-01")),
                ("dateFin", models.DateField(default="9999-12-31")),
            ],
        ),
        migrations.RemoveField(model_name="employe", name="administrateur",),
        migrations.RemoveField(model_name="employe", name="dateEmbauche",),
        migrations.RemoveField(model_name="employe", name="id",),
        migrations.AddField(
            model_name="employe",
            name="numeroEmploye",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="employe",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="gestionPersonnel.employe",
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="dateAjout",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 11, 21, 47, 54, 811474, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="TermPaie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.FloatField(default=0)),
                ("bonus", models.FloatField(default=0)),
                ("dateDebut", models.DateField(default="1991-01-01")),
                ("dateFin", models.DateField(default="9999-12-31")),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionPersonnel.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TermEmploi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateDebut", models.DateField()),
                ("dateFin", models.DateField(default="9999-12-31")),
                ("raisonFin", models.CharField(default="N/A", max_length=100)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionPersonnel.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Poste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("categorie", models.CharField(max_length=100)),
                ("niveau", models.IntegerField()),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="gestionPersonnel.departement",
                    ),
                ),
                (
                    "employePoste",
                    models.ManyToManyField(
                        through="gestionPersonnel.EmployePoste",
                        to="gestionPersonnel.employe",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employeposte",
            name="employe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gestionPersonnel.employe",
            ),
        ),
        migrations.AddField(
            model_name="employeposte",
            name="poste",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="gestionPersonnel.poste",
            ),
        ),
    ]
