# Generated by Django 4.1 on 2023-02-11 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionPersonnel", "0008_departement_employeposte_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="dateAjout",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 11, 21, 50, 51, 984510, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
