# Generated by Django 4.1 on 2023-02-11 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionPersonnel", "0009_alter_employe_dateajout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="dateAjout",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 11, 22, 25, 34, 144979, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
