# Generated by Django 4.1 on 2023-02-11 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionPersonnel", "0010_alter_employe_dateajout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="dateAjout",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 11, 22, 27, 51, 961094, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="termemploi",
            name="raisonFin",
            field=models.CharField(default="Actif(ve)", max_length=100),
        ),
    ]
