# Generated by Django 4.1 on 2023-02-11 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionPersonnel", "0011_alter_employe_dateajout_alter_termemploi_raisonfin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="dateAjout",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 11, 22, 32, 23, 355984, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
