# Generated by Django 4.1 on 2023-02-12 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionPersonnel", "0012_alter_employe_dateajout"),
    ]

    operations = [
        migrations.AddField(
            model_name="termemploi",
            name="type",
            field=models.CharField(
                choices=[("P", "Permanent"), ("C", "Contractuel")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="termpaie",
            name="raisonPaie",
            field=models.CharField(default="Termes actuels", max_length=500),
        ),
        migrations.AlterField(
            model_name="employe",
            name="dateAjout",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 12, 2, 29, 26, 158233, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="termemploi",
            name="raisonFin",
            field=models.CharField(default="Termes actuels", max_length=100),
        ),
    ]
