# Generated by Django 4.1.7 on 2023-03-12 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionPersonnel", "0022_alter_employe_dateajout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="dateAjout",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 12, 18, 42, 18, 123367, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
