# Generated by Django 4.1.7 on 2023-04-02 01:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("acceuil", "0005_pays_ville_delete_pays_dim_delete_ville_dim"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeroEmploye", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("prenom", models.CharField(max_length=50)),
                ("nom", models.CharField(max_length=50)),
                ("dateNaissance", models.DateField(blank=True, null=True)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("H", "HOMME"), ("F", "FEMME")], max_length=1
                    ),
                ),
                (
                    "adresseDomicile",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("telephone", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "pays",
                    models.ForeignKey(
                        blank=True,
                        default=127,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="acceuil.pays",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        default=999,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="personnel.employe",
                    ),
                ),
                (
                    "ville",
                    models.ForeignKey(
                        blank=True,
                        default=22187,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="acceuil.ville",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "departementParent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="personnel.departement",
                    ),
                ),
            ],
        ),
    ]
