# Generated by Django 4.1.7 on 2023-04-02 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("responsable", models.BooleanField(default=False)),
                ("niveau", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="employe",
            name="bonus",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="employe",
            name="dateEmbauche",
            field=models.DateField(default="1991-01-01"),
        ),
        migrations.AddField(
            model_name="employe",
            name="dateFinEmploi",
            field=models.DateField(default="9999-12-31"),
        ),
        migrations.AddField(
            model_name="employe",
            name="departement",
            field=models.ForeignKey(
                default=999,
                on_delete=django.db.models.deletion.RESTRICT,
                to="personnel.departement",
            ),
        ),
        migrations.AddField(
            model_name="employe",
            name="raisonFinEmploi",
            field=models.CharField(
                choices=[
                    ("R", "retraite"),
                    ("V", "Fin volontaire"),
                    ("I", "Fin involontaire"),
                    ("C", "Fin contrat"),
                    ("A", "Autre raison"),
                    ("N/A", "Pas applicable"),
                ],
                default="N/A",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="employe",
            name="salaireBase",
            field=models.FloatField(default=25000),
        ),
        migrations.AddField(
            model_name="employe",
            name="typeEmploi",
            field=models.CharField(
                choices=[("P", "Permanent"), ("C", "Contractuel")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="employe",
            name="poste",
            field=models.ForeignKey(
                default=999,
                on_delete=django.db.models.deletion.RESTRICT,
                to="personnel.poste",
            ),
        ),
    ]
