# Generated by Django 4.1.7 on 2023-04-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0005_remove_poste_responsable"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermesEmploi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateEmbauche", models.DateField(default="1991-01-01")),
                ("dateFinEmploi", models.DateField(default="9999-12-31")),
                (
                    "raisonFinEmploi",
                    models.CharField(
                        choices=[
                            ("R", "retraite"),
                            ("V", "Fin volontaire"),
                            ("I", "Fin involontaire"),
                            ("C", "Fin contrat"),
                            ("n/a", "non-applicable"),
                        ],
                        default="n/a",
                        max_length=3,
                    ),
                ),
                ("raisonFinDetails", models.TextField(default="n/a", max_length=200)),
                (
                    "typeEmploi",
                    models.CharField(
                        choices=[("P", "Permanent"), ("C", "Contractuel")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("salaire", models.FloatField(default=25000)),
                ("bonus", models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(model_name="employe", name="bonus",),
        migrations.RemoveField(model_name="employe", name="dateEmbauche",),
        migrations.RemoveField(model_name="employe", name="dateFinEmploi",),
        migrations.RemoveField(model_name="employe", name="raisonFinEmploi",),
        migrations.RemoveField(model_name="employe", name="salaireBase",),
        migrations.RemoveField(model_name="employe", name="typeEmploi",),
    ]
