# Generated by Django 4.1.7 on 2023-04-15 20:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=50, null=True)),
                ("designation", models.CharField(max_length=100)),
                (
                    "uniteDeMesure",
                    models.CharField(
                        choices=[
                            ("u", "unite"),
                            ("m", "metre lineaire"),
                            ("m2", "metre carre"),
                            ("m3", "metre cube"),
                            ("n/a", "non-applicable"),
                        ],
                        default="m",
                        max_length=50,
                    ),
                ),
                (
                    "uniteDeQuantification",
                    models.CharField(
                        choices=[
                            ("u", "unite"),
                            ("m", "metre lineaire"),
                            ("m2", "metre carre"),
                            ("m3", "metre cube"),
                            ("barre", "barre 5,8m"),
                            ("n/a", "non-applicable"),
                        ],
                        default="u",
                        max_length=50,
                    ),
                ),
                ("prixDeRevient", models.FloatField(blank=True, null=True)),
                ("prixDeVente", models.FloatField(blank=True, null=True)),
                ("fabriquant", models.CharField(blank=True, max_length=100, null=True)),
                ("indArticleFab", models.BooleanField(default=False)),
                ("info", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("classe", models.CharField(max_length=50)),
                ("info", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=50, verbose_name="Prenom")),
                ("nom", models.CharField(max_length=50, verbose_name="Nom")),
                (
                    "nomEntreprise",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nom de l'entreprise",
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Telephone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "info",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Autres infos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Couleur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("couleur", models.CharField(max_length=50)),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                ("info", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "departementParent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="api.departement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Devis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(
                            2023,
                            4,
                            15,
                            20,
                            58,
                            35,
                            561006,
                            tzinfo=datetime.timezone.utc,
                        ),
                        verbose_name="Date",
                    ),
                ),
                (
                    "remise",
                    models.FloatField(
                        blank=True, default=0, null=True, verbose_name="Remise %"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("largeur", models.IntegerField()),
                ("hauteur", models.IntegerField()),
                ("epaisseur", models.IntegerField(blank=True, null=True)),
                ("volume", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeroEmploye", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("prenom", models.CharField(max_length=50)),
                ("nom", models.CharField(max_length=50)),
                ("dateNaissance", models.DateField(default="1991-01-01")),
                (
                    "sexe",
                    models.CharField(
                        choices=[("H", "HOMME"), ("F", "FEMME")], max_length=1
                    ),
                ),
                ("adresseDomicile", models.CharField(default="Bamako", max_length=100)),
                ("telephone", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "departement",
                    models.ForeignKey(
                        default=999,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="api.departement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pays", models.CharField(max_length=50)),
                ("abbrev", models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Poste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("niveau", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TermesEmploi",
            fields=[
                (
                    "employe",
                    models.OneToOneField(
                        default=999,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.employe",
                    ),
                ),
                ("dateEmbauche", models.DateField(default="1991-01-01")),
                ("dateFinEmploi", models.DateField(default="9999-12-31")),
                (
                    "raisonFinEmploi",
                    models.CharField(
                        choices=[
                            ("R", "Retraite"),
                            ("V", "Fin volontaire"),
                            ("I", "Fin involontaire"),
                            ("C", "Fin contrat"),
                            ("n/a", "non-applicable"),
                        ],
                        default="n/a",
                        max_length=3,
                    ),
                ),
                ("raisonFinDetails", models.TextField(default="n/a", max_length=200)),
                (
                    "typeEmploi",
                    models.CharField(
                        choices=[("P", "Permanent"), ("C", "Contractuel")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("salaire", models.FloatField(default=25000)),
                ("bonus", models.FloatField(default=0)),
                (
                    "dateMisAJour",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mis-a-jour"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ville",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ville", models.CharField(max_length=50)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                (
                    "pays",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.pays"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nomenclature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qtiteArticleBrutReq", models.IntegerField(default=0)),
                (
                    "produitBrut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produitBrut",
                        to="api.article",
                    ),
                ),
                (
                    "produitFini",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produitFini",
                        to="api.article",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employe",
            name="pays",
            field=models.ForeignKey(
                default=127, on_delete=django.db.models.deletion.RESTRICT, to="api.pays"
            ),
        ),
        migrations.AddField(
            model_name="employe",
            name="poste",
            field=models.ForeignKey(
                default=999,
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.poste",
            ),
        ),
        migrations.AddField(
            model_name="employe",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.employe",
            ),
        ),
        migrations.AddField(
            model_name="employe",
            name="ville",
            field=models.ForeignKey(
                default=22187,
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.ville",
            ),
        ),
        migrations.CreateModel(
            name="DevisArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.FloatField(default=0, verbose_name="Quantite")),
                (
                    "article",
                    models.ForeignKey(
                        default=999,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.article",
                        verbose_name="Article",
                    ),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        default=999,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.devis",
                        verbose_name="Numero du devis",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="devis",
            name="agentCommercial",
            field=models.ForeignKey(
                default=999,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="createurDevis",
                to="api.employe",
                verbose_name="Nom de l'agent comm.",
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="article",
            field=models.ManyToManyField(
                through="api.DevisArticle", to="api.article", verbose_name="Article"
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="client",
            field=models.ForeignKey(
                default=999,
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.client",
                verbose_name="Nom du client",
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="responsable",
            field=models.ForeignKey(
                default=999,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="responsableTravail",
                to="api.employe",
                verbose_name="Nom du resp.",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="pays",
            field=models.ForeignKey(
                blank=True,
                default=127,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.pays",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="ville",
            field=models.ForeignKey(
                blank=True,
                default=22187,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.ville",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="articleFabrique",
            field=models.ManyToManyField(
                blank=True, null=True, through="api.Nomenclature", to="api.article"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="classe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.classe"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="couleur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="api.couleur"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="dimension",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="api.dimension"
            ),
        ),
    ]
