# Generated by Django 4.1.7 on 2023-05-21 20:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_employe_telephone2_alter_client_pays_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devis",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 5, 21, 20, 40, 27, 744766, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date",
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="departement",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.departement",
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="poste",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.RESTRICT, to="api.poste"
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="sexe",
            field=models.CharField(
                choices=[("H", "HOMME"), ("F", "FEMME")], default="H", max_length=1
            ),
        ),
    ]
