# Generated by Django 4.1.7 on 2023-05-21 21:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_devis_date_alter_employe_departement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devis",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 5, 21, 21, 40, 54, 903565, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date",
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="pays",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.RESTRICT, to="api.pays"
            ),
        ),
        migrations.AlterField(
            model_name="employe",
            name="ville",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.RESTRICT, to="api.ville"
            ),
        ),
    ]
