# Generated by Django 4.1.6 on 2023-05-27 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_devis_date_alter_employe_pays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 27, 16, 55, 54, 685188, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
