# Generated by Django 4.1.6 on 2023-06-03 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_devis_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 3, 21, 21, 59, 769285, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
