# Generated by Django 4.1.7 on 2023-06-04 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_devis_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devis",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 4, 2, 15, 57, 726427, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date",
            ),
        ),
    ]
