# Generated by Django 4.1.7 on 2023-06-25 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_devis_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="employe", name="pays",),
        migrations.AlterField(
            model_name="devis",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 25, 19, 44, 31, 788509, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date",
            ),
        ),
    ]
