# Generated by Django 4.1.7 on 2023-04-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "personnel",
            "0003_alter_employe_adressedomicile_alter_employe_bonus_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="adresseDomicile",
            field=models.CharField(default="Bamako", max_length=100),
        ),
    ]
