# Generated by Django 4.1.7 on 2023-04-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0004_alter_employe_adressedomicile"),
    ]

    operations = [
        migrations.RemoveField(model_name="poste", name="responsable",),
    ]
