# Generated by Django 4.1.7 on 2023-03-26 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("classe", models.CharField(max_length=50)),
                ("indProduitFini", models.BooleanField()),
                ("info", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Couleur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("couleur", models.CharField(max_length=50)),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                ("info", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("largeur", models.IntegerField()),
                ("hauteur", models.IntegerField()),
                ("epaisseur", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=50, null=True)),
                ("designation", models.CharField(max_length=100)),
                (
                    "uniteDeMesure",
                    models.CharField(
                        choices=[
                            ("u", "unite"),
                            ("m", "metre lineaire"),
                            ("m2", "metre carre"),
                            ("m3", "metre cube"),
                            ("n/a", "non-applicable"),
                        ],
                        default="m",
                        max_length=50,
                    ),
                ),
                (
                    "uniteDeQuantification",
                    models.CharField(
                        choices=[
                            ("u", "unite"),
                            ("m", "metre lineaire"),
                            ("m2", "metre carre"),
                            ("m3", "metre cube"),
                            ("barre", "barre 5,8m"),
                            ("n/a", "non-applicable"),
                        ],
                        default="u",
                        max_length=50,
                    ),
                ),
                ("fabriquant", models.CharField(blank=True, max_length=100, null=True)),
                ("info", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventaires_et_stock.classe",
                    ),
                ),
                (
                    "couleur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="inventaires_et_stock.couleur",
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="inventaires_et_stock.dimension",
                    ),
                ),
            ],
        ),
    ]
