# Generated by Django 4.1.7 on 2023-04-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventaires_et_stock", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="classe", name="indProduitFini",),
        migrations.AddField(
            model_name="classe",
            name="indFabricationReq",
            field=models.BooleanField(default=0),
        ),
    ]
