# Generated by Django 4.1.7 on 2023-04-15 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventaires_et_stock", "0002_remove_classe_indproduitfini_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="prixDeRevient",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="prixDeVente",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dimension",
            name="volume",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Nomenclature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qtiteArticleBrutReq", models.IntegerField(default=0)),
                ("quantiteProduitBrut", models.FloatField(default=0)),
                (
                    "produitBrut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produitBrut",
                        to="inventaires_et_stock.article",
                    ),
                ),
                (
                    "produitFini",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produitFini",
                        to="inventaires_et_stock.article",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="articleFabrique",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                through="inventaires_et_stock.Nomenclature",
                to="inventaires_et_stock.article",
            ),
        ),
    ]
