# Generated by Django 4.1.6 on 2023-02-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClasseMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClasseProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largeur', models.FloatField()),
                ('hauteur', models.FloatField()),
                ('profondeur', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=50)),
                ('personneRelation', models.CharField(max_length=100)),
                ('fournisseurFabriquant', models.CharField(choices=[('N', 'Non'), ('O', 'Oui')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('uniteDeMesure', models.CharField(max_length=50)),
                ('uniteDeQuantification', models.CharField(max_length=50)),
                ('cout', models.FloatField(default=10000)),
                ('prix', models.FloatField(default=17000)),
                ('fabriquant', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=200)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionStock.categoriemat')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionStock.classemat')),
                ('couleur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionStock.couleur')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionStock.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiteMateriel', models.FloatField(default=1)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionStock.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('uniteDeMesure', models.CharField(max_length=50)),
                ('uniteDeQuantification', models.CharField(max_length=50)),
                ('cout', models.FloatField(default=10000)),
                ('prix', models.FloatField(default=17000)),
                ('info', models.CharField(max_length=200)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionStock.classeprod')),
                ('couleur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionStock.couleur')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionStock.dimension')),
                ('materiel', models.ManyToManyField(through='gestionStock.Nomenclature', to='gestionStock.materiel')),
            ],
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestionStock.produit'),
        ),
    ]
