# Generated by Django 4.1.7 on 2023-02-20 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategorieMat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categorie", models.CharField(max_length=50)),
                ("info", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CategorieProd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categorie", models.CharField(max_length=50)),
                ("info", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClasseMat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("classe", models.CharField(max_length=50)),
                ("info", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClasseProd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("classe", models.CharField(max_length=50)),
                ("info", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Couleur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("info", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("largeur", models.IntegerField(default=0)),
                ("hauteur", models.IntegerField(default=0)),
                ("profondeur", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("adresse", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telephone", models.CharField(blank=True, max_length=50, null=True)),
                ("pays", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "personneRelation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fournisseurFabriquant", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Materiel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "uniteDeMesure",
                    models.CharField(
                        choices=[
                            ("m", "metre"),
                            ("m2", "mettre carre"),
                            ("m3", "mettre cube"),
                            ("n/a", "pas applicable"),
                        ],
                        default="m",
                        max_length=50,
                    ),
                ),
                (
                    "uniteDeQuantification",
                    models.CharField(
                        choices=[
                            ("u", "unite"),
                            ("m", "metre"),
                            ("m2", "mettre carre"),
                            ("m3", "mettre cube"),
                            ("n/a", "pas applicable"),
                        ],
                        default="u",
                        max_length=50,
                    ),
                ),
                ("cout", models.FloatField(default=10000)),
                ("prix", models.FloatField(default=17000)),
                ("fabriquant", models.CharField(blank=True, max_length=100, null=True)),
                ("info", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "characteristiques",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionStock.categoriemat",
                    ),
                ),
                (
                    "couleur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="gestionStock.couleur",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="gestionStock.fournisseur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nomenclature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantiteMateriel", models.FloatField(default=1)),
                (
                    "materiel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionStock.materiel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "uniteDeMesure",
                    models.CharField(
                        choices=[
                            ("m", "metre"),
                            ("m2", "mettre carre"),
                            ("m3", "mettre cube"),
                            ("n/a", "pas applicable"),
                        ],
                        default="m",
                        max_length=50,
                    ),
                ),
                (
                    "uniteDeQuantification",
                    models.CharField(
                        choices=[
                            ("u", "unite"),
                            ("m", "metre"),
                            ("m2", "mettre carre"),
                            ("m3", "mettre cube"),
                            ("n/a", "pas applicable"),
                        ],
                        default="u",
                        max_length=50,
                    ),
                ),
                ("cout", models.FloatField(default=10000)),
                ("prix", models.FloatField(default=17000)),
                ("info", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "characteristiques",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionStock.categorieprod",
                    ),
                ),
                (
                    "couleur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="gestionStock.couleur",
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="gestionStock.dimension",
                    ),
                ),
                (
                    "materiel",
                    models.ManyToManyField(
                        through="gestionStock.Nomenclature", to="gestionStock.materiel"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="nomenclature",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gestionStock.produit"
            ),
        ),
        migrations.AddField(
            model_name="categorieprod",
            name="classe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestionStock.classeprod",
            ),
        ),
        migrations.AddField(
            model_name="categoriemat",
            name="classe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestionStock.classemat",
            ),
        ),
    ]
