# Generated by Django 4.1.6 on 2023-02-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0003_pays_remove_ville_abbrev_alter_ville_pays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couleur',
            old_name='nom',
            new_name='couleur',
        ),
    ]
