# Generated by Django 4.1.6 on 2023-02-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0003_alter_dimension_hauteur_alter_dimension_largeur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='hauteur',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='largeur',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='profondeur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
