# Generated by Django 4.1.6 on 2023-02-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0004_rename_nom_couleur_couleur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiel',
            old_name='characteristiques',
            new_name='categorieMat',
        ),
    ]
