# Generated by Django 4.1.7 on 2023-03-11 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestionStock", "0005_rename_characteristiques_materiel_categoriemat"),
    ]

    operations = [
        migrations.AddField(
            model_name="fournisseur",
            name="pays",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="gestionStock.pays",
            ),
        ),
    ]
