# Generated by Django 4.1.6 on 2023-02-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0005_alter_materiel_fournisseur_alter_produit_couleur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='uniteDeQuantification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='uniteDeMesure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='uniteDeQuantification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
