# Generated by Django 4.1.7 on 2023-03-12 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionStock", "0008_coutprixmat_remove_materiel_fabriquant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimension",
            name="info",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="coutprixmat",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 12, 3, 8, 50, 681169, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
