# Generated by Django 4.1.7 on 2023-03-12 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionStock", "0009_dimension_info_alter_coutprixmat_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="materiel",
            name="fabriquant",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="coutprixmat",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 12, 3, 11, 52, 679134, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
