# Generated by Django 4.1.7 on 2023-03-12 03:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestionStock", "0010_materiel_fabriquant_alter_coutprixmat_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="coutprixmat",
            name="materiel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestionStock.materiel",
            ),
        ),
        migrations.AlterField(
            model_name="coutprixmat",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 12, 3, 14, 7, 46181, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
