# Generated by Django 4.1.7 on 2023-03-12 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionStock", "0013_alter_coutprixmat_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coutprixmat",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 12, 3, 32, 35, 822755, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
