# Generated by Django 4.1.7 on 2023-03-12 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestionStock", "0015_nomenclature_materiel_unitedemesure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="materiel",
            name="dimension",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="gestionStock.dimension",
            ),
        ),
        migrations.AlterField(
            model_name="nomenclature",
            name="quantiteMateriel",
            field=models.FloatField(default=0),
        ),
    ]
