# Generated by Django 4.1.7 on 2023-03-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionStock", "0016_materiel_dimension_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="uniteDeMesure",
            field=models.CharField(
                choices=[
                    ("u", "unite"),
                    ("m", "metre lineaire"),
                    ("m2", "metre carre"),
                    ("m3", "metre cube"),
                    ("n/a", "pas applicable"),
                ],
                default="m",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="materiel",
            name="uniteDeQuantification",
            field=models.CharField(
                choices=[
                    ("u", "unite"),
                    ("m", "metre lineaire"),
                    ("m2", "metre carre"),
                    ("m3", "metre cube"),
                    ("barre", "barre 5,8m"),
                    ("n/a", "pas applicable"),
                ],
                default="u",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="uniteDeQuantification",
            field=models.CharField(
                choices=[
                    ("u", "unite"),
                    ("m", "metre lineaire"),
                    ("m2", "metre carre"),
                    ("m3", "metre cube"),
                    ("barre", "barre 5,8m"),
                    ("n/a", "pas applicable"),
                ],
                default="u",
                max_length=50,
            ),
        ),
    ]
