# Generated by Django 4.1.7 on 2023-03-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceuil", "0003_pays_dim_delete_pays"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ville_Dim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ville", models.CharField(max_length=50)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
            ],
            options={"db_table": '"communs". "ville_dim"', "managed": False,},
        ),
    ]
