# Generated by Django 4.1.7 on 2023-04-02 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devis",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 4, 2, 2, 20, 58, 287125, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
