# Generated by Django 4.1.7 on 2023-04-15 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0011_alter_devis_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devis",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 4, 15, 15, 44, 57, 866514, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date",
            ),
        ),
    ]
