# Generated by Django 4.1.7 on 2023-03-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acceuil", "0002_pays_delete_pays_dim"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pays_Dim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pays", models.CharField(max_length=50)),
                ("abbrev", models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={"db_table": '"communs". "pays_dim"', "managed": False,},
        ),
        migrations.DeleteModel(name="Pays",),
    ]
